name: Build And Test the source code

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: build_and_run_ut
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Instal prerequisites
        run: sudo apt-get install -y build-essential cmake openssl libssl-dev
      - name: build cmake_example
        run: cd cmake_example && mkdir build && cd build && cmake .. && cmake --build . && ./myAwesomeApp
      - name: build cmake_example_openssl
        run: cd cmake_example_openssl && mkdir build && cd build && cmake .. && cmake --build . && ./myAwesomeApp
      - name: build cmake_multiprojects
        run: cd cmake_multiprojects && mkdir build && cd build && cmake .. && cmake --build . && ./app/myAwesomeApp
      - name: build cmake_multiprojects_gtest
        run: cd cmake_multiprojects_gtest && mkdir build && cd build && cmake .. && cmake --build . && ctest && ./app/myAwesomeApp
      